### ISSUE TITLE
Support for callouts

### ISSUE THREAD

**Issue by alfredo-perez-sp** [johackim/remark-obsidian#3]
It will be good to support callouts https://help.obsidian.md/How+to/Use+callouts

**Comment by ispringle** [comment]
Here's my naive solution to this https://github.com/ispringle/sylvan/blob/master/src/utils/remark-obsidian.js#L95

**Comment by johackim** [comment]
Hello @ispringle, I've added support for callouts, thanks for your code inspiration 😉
